name: flutter_kurdish_localization_example
description: "Demonstrates how to use the flutter_kurdish_localization plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  fancy_snackbar:
    git: https://github.com/MR0100/fancy_snackbar.git
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_kurdish_localization:
    path: ../
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/lang/en.json
    - lib/lang/ckb.json
    - lib/lang/ar.json
    - assets/images/
    - assets/flags/
