name: flutter_kurdish_localization
description: Flutter Central Kurdish Localization in easy steps, simple ways to localize and translate your app to Central Kurdish.
version: 1.1.1
homepage: https://github.com/aminsamad/flutter_kurdish_localization

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.38.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: '>=0.19.0 <0.21.0'
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_kurdish_localization
        pluginClass: FlutterKurdishLocalizationPlugin
      ios:
        pluginClass: FlutterKurdishLocalizationPlugin
      linux:
        pluginClass: FlutterKurdishLocalizationPlugin
      macos:
        pluginClass: FlutterKurdishLocalizationPlugin
      windows:
        pluginClass: FlutterKurdishLocalizationPluginCApi
      web:
        pluginClass: FlutterKurdishLocalizationWeb
        fileName: flutter_kurdish_localization_web.dart
